### ISSUE TITLE
How use this plugin for django admin?

### ISSUE THREAD

**Issue by batazor** [gen1us2k/django_ory_auth#4]
The plugin works well but doesn't work with the admin login, any ideas on how to fix this?

**Comment by gen1us2k** [comment]
Hello. Have you tried to change `is_superuser` and other flags for the user you wanna authenticate? @batazor

**Comment by batazor** [comment]
@gen1us2k Yes, that's right I understand the best option is to write your own `SettingsBackend` and add the necessary checks there?
